services:
  frontend:
    image: hasanmar/sudoku-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: hasanmar/sudoku-backend:latest
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:alpine:latest
    ports:
      - "6379:6379"